train:
  audio:
    MelSpectrogram:
      sample_rate: 16000  # for the predefined_dataset SPEECHCOMMANDS
      n_mels: 64  # for the predefined_dataset SPEECHCOMMANDS
    AmplitudeToDB:
  vision:
    Resize: 
      - 256
      - 256

val:
  audio:
    MelSpectrogram:
      sample_rate: 16000  # for the predefined_dataset SPEECHCOMMANDS
      n_mels: 64  # for the predefined_dataset SPEECHCOMMANDS
    AmplitudeToDB:
  vision:
    Resize: 
      - 256
      - 256

test:
  audio:
    MelSpectrogram:
      sample_rate: 16000  # for the predefined_dataset SPEECHCOMMANDS
      n_mels: 64  # for the predefined_dataset SPEECHCOMMANDS
    AmplitudeToDB:
  vision:
    Resize: 
      - 256
      - 256

predict:
  audio:
    MelSpectrogram:
      sample_rate: 16000  # for the predefined_dataset SPEECHCOMMANDS
      n_mels: 64  # for the predefined_dataset SPEECHCOMMANDS
    AmplitudeToDB:
  vision:
    Resize: 
      - 256
      - 256